name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      number-of-agents: 3
      init-commands: |
        mkdir -p ./.yarn/cache
        yarn exec nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn exec nx-cloud record -- yarn exec nx workspace-lint
        yarn exec nx-cloud record -- yarn exec nx format:check
      parallel-commands-on-agents: |
        yarn exec nx affected --target=lint --parallel=3
        yarn exec nx affected --target=test --parallel=3 -- --ci --code-coverage
        yarn exec nx affected --target=build --parallel=3

  # e2e:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Chrome
  #       uses: cypress-io/github-action@v4
  #       timeout-minutes: 10
  #       with:
  #         install-command: yarn --immutable --silent
  #         command: yarn e2e
  #         browser: chrome

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3
